name: NNSelfLearn
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.11
  - numpy
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - matplotlib
  - ipykernel
  - pandas
  - scipy
  - scikit-learn
  - pytest
prefix: /cs/student/projects1/ml/2024/sdodds/miniconda3/envs/NNSelfLearn
